### ISSUE TITLE
Wrong flake8 version constraint

### ISSUE THREAD

**Issue by randolf-scholz** [conda-forge/flake8-annotations-feedstock#12]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Original repo: `flake8 = ">=3.7, <5.0"`

https://github.com/sco1/flake8-annotations/blob/951be2c032c301a67cf93c0c180a6adb5fa12b5d/pyproject.toml#L38

Conda-forge feedstock: `flake8 >=3.7, <4.0`

https://github.com/conda-forge/flake8-annotations-feedstock/blob/4b20428ac4c98c6fd7e3f363bf35255479cc453f/recipe/meta.yaml#L27

### Installed packages

```shell
na
```

### Environment info

```shell
na
```

**Comment by apmorton** [comment]
Fixed in #23
